### ISSUE TITLE
Zellij configuration

### ISSUE THREAD

**Issue by wiraki** [Nacho114/harpoon#11]
Hello, cool plugin, thanks for sharing!

This is not really an issue, sorry for creating one but Discussions is not enabled. I was only wondering if you could share your Zellij configuration? I saw your `dotfiles` repo but I don't think Zellij's config was included there?

Thanks!

**Comment by m4siri** [comment]
Hello there if this comment is referring to me i have just updated my repository [dotfiles](https://github.com/sirimhrzn/dotfiles/).
It might not work out of the box due to hardcoded file paths and is very minimal.

**Comment by m-pauper** [comment]
Thanks! Not sure if it was you or Nacho114, whoever made the usage gif in the readme :) 

Initially I noticed the different menu style in Zellij, just saw in the dotfiles you linked that there are a few Zellij plugins, I guess that is my answer! :+1: 

> It might not work out of the box due to hardcoded file paths and is very minimal
No worries, I just wanted to get ideas for Zellij config, I am not going to copy paste as is. 

Feel free to close this issue. Thanks again!

**Comment by wiraki** [comment]
Thanks! Not sure if it was you or Nacho114, whoever made the usage gif in the readme :) 

Initially I noticed the different menu style in Zellij, just saw in the dotfiles you linked that there are a few Zellij plugins, I guess that is my answer! :+1: 

> It might not work out of the box due to hardcoded file paths and is very minimal.

No worries, I just wanted to get ideas for Zellij config, I am not going to copy paste as is.
