### ISSUE TITLE
Provide release binaries?

### ISSUE THREAD

**Issue by dit7ya** [Nacho114/harpoon#2]
Hi,

Thanks for the package. Would it be possible to release the compiled binaries via GitHub?

**Comment by Nacho114** [comment]
Hey!

You are welcome :). Do you mean the `.wasm` binary? If so, sure I could add it.

**Comment by dit7ya** [comment]
Yes exactly, like this - https://github.com/dj95/zjstatus/releases

**Comment by Nacho114** [comment]
Done, you can find it [here](https://github.com/Nacho114/harpoon/releases/tag/v0.1.0).

Enjoy :)
