### ISSUE TITLE
Failed to start plugin 5 for 1 client

### ISSUE THREAD

**Issue by abneb** [Nacho114/harpoon#3]
I'm facing this issue when I try to work with the plugin. 
I'm on Zellij 037.2.

![image](https://github.com/Nacho114/harpoon/assets/69637662/45d94ee5-4a5e-4916-b3bf-9188eb61e0b4)

**Comment by Nacho114** [comment]
You need to be running Zellij 0.38.0, I forgot to add this in the docs, sorry about that! I'll add it now :)

**Comment by abneb** [comment]
Hey man! Don'n worry. I actually figure out a few minutes later reading the issues on Room. So I already done it. 
Good that is on documentation now.
