### ISSUE TITLE
failed to start plugin 1 for clinet 1

### ISSUE THREAD

**Issue by abdelkareemkobo** [Nacho114/harpoon#4]
![image](https://github.com/Nacho114/harpoon/assets/72500236/e620053f-7c1a-4aeb-899a-65d88ca2c5f1)
How to solve this issue while i am trying to install harpoon

**Comment by Nacho114** [comment]
What version of Zellij are you running?

**Comment by Nacho114** [comment]
Will close since this looks like an outdated version of Zellij us running
