### ISSUE TITLE
[ FIXED ]Do not compile

### ISSUE THREAD

**Issue by MrMic** [Nacho114/harpoon#5]
I have just followed the instructions:
cd harpoon
cargo build --release
mkdir -p ~/.config/zellij/plugins/
mv target/wasm32-wasi/release/harpoon.wasm ~/.config/zellij/plugins/

and got this:
   Compiling libc v0.2.147
   Compiling autocfg v1.1.0
   Compiling proc-macro2 v1.0.63
   Compiling quote v1.0.29
   Compiling unicode-ident v1.0.9
   Compiling memchr v2.5.0
   Compiling version_check v0.9.4
   Compiling cfg-if v1.0.0
error[E0463]: can't find crate for `core`
  |
  = note: the `wasm32-wasi` target may not be installed
  = help: consider downloading the target with `rustup target add wasm32-wasi`

error[E0463]: can't find crate for `compiler_builtins`

For more information about this error, try `rustc --explain E0463`.
error: could not compile `cfg-if` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...

Thanks for fixing it.
Rgds,
Michaël C.

**Comment by MrMic** [comment]
In fact, I have not noticed to add:
`
$> rustup target add wasm32-wasi
`

Sorry for the noise.

**Comment by Nacho114** [comment]
No worries, thanks for adding the solution, now it's useful to others as well (so it was not noise :p)
